### ISSUE TITLE
Converting ai to svg

### ISSUE THREAD

**Issue by hansfindel** [edwinv710/cloudconvert-ruby#1]
I am trying to convert from "ai" to "svg". 

I tested the web-application and it can do it. But when I try with the gem provided, it throws the following error:  {:error=>"Please provide input and output format for the conversion!", :code=>400} 

It works for other convertion formats, but when I set the input format to "ai", it throws that error.

**Comment by edwinv710** [comment]
@hansfindel Thank you for bringing this up. I patched it up and ran a few test. Ai files should be converting. :+1:

**Comment by hansfindel** [comment]
Great!
Just tested it and now it works
