### ISSUE TITLE
Accept other process than only `convert`

### ISSUE THREAD

**Issue by pedrofs** [edwinv710/cloudconvert-ruby#4]
CloudConvert accepts other processes.

From [API docs](https://cloudconvert.com/api/conversions#create)
> Other possible values are info, combine, archive and extract.

I personally would like to use `info` process.

I'll setup a PR for accomplishing that.

**Comment by edwinv710** [comment]
Thank you for the PR. I'll be doing some upgrades this week to add more features including the ones in the PR. In the meantime, my advice is to use your fork as the git origin in the Gemfile.

**Comment by pedrofs** [comment]
Hi Edwinv, after testing my PR directly from by clone I realized that the change is not a simple as it sounds and the current implementation doesn't work well.

I would like to help you on extending the gem but unfortunately the next two weeks are a tight time to me.

Best.
